### ISSUE TITLE
multiplayer channel; from 16patsle

### ISSUE THREAD

**Issue by jdotrjs** [phaser-discord/administration#17]
Suggested by 16patsle#7801 / 103894773261160448, on Monday, March 12, 2018, 09:52 UTC:
>Would having a channel for multiplayer-stuff make sense?

**Comment by 16patsle** [comment]
<img width="598" alt="skjermbilde 2018-03-12 kl 11 02 07" src="https://user-images.githubusercontent.com/7686840/37277444-e6cbc84a-25e4-11e8-9ce4-11933a117da2.png">

**Comment by jdotrjs** [comment]
folded into aggregate
