### ISSUE TITLE
Some system to (relatively automatically) track ideas that go into #discord-feedback

### ISSUE THREAD

**Issue by jdotrjs** [phaser-discord/administration#2]
In slack there is a `reactji` or some other dumb name that you can wire up which sends the reacted message to another channel. Similar to that behavior it'd be nice if we had a bot that could file issues here with some label (`idea`, `discuss`) when it saw one of us react w/ a specific emoji (:spiral_notepad:?) to a comment in #discord-feedback)

**Comment by 16patsle** [comment]
Nice idea. I configured webhooks (inspired by your idea, but in reverse, sort of), so activity on this repo should be visible on the admin channel. Maybe we'll need to tweak some stuff later

**Comment by 16patsle** [comment]
(Test comment to see if it works)

**Comment by 16patsle** [comment]
I've done some research, and it would totally be possible to make such a bot (there's a discord event called messageReactionAdd). The biggest issue would be where to host it.

**Comment by 16patsle** [comment]
Did some playing around with this @jdotjs, and managed to make a working bot (in node.js). Haven't made it available anywhere yet, but you can see the issues it created over at https://github.com/16patsle/testing/issues

Actually kinda fun learning both the discord.js API and the Github API at the same time

**Comment by jdotrjs** [comment]
I'll try to get this set up and running on a host I've already got _in the cloud_ this weekend.

**Comment by 16patsle** [comment]
Nice. I just realized I can edit your comment, that's funny...

**Comment by jdotrjs** [comment]
Yea, I had been thinking about how we'd want to capture context but that felt like a :wave: future problem :wave: for the moment.

I get caught up on how we'd track which issue the secondary tag would be attached to or how to tie content back to an issue when discussion has happened before it got filed.
