### ISSUE TITLE
MyGameBuilder channel; suggestion from robmuh

### ISSUE THREAD

**Issue by jdotrjs** [phaser-discord/administration#29]
Suggested by robmuh#6072 / 99992896790368256, on Wednesday, April 18, 2018, 19:37 UTC:
>Hey there, how would you feel about adding a #mgb channel for MyGameBuilder (the cloud based IDE for Phaser development) https://build.games (which I just discovered and with which I have no official affiliation). It is an amazing project that has tremendous potential.

**Comment by 16patsle** [comment]
Folded into #25
